apiVersion: v1
kind: Namespace
metadata:
  name: sdm
  labels:
    app.kubernetes.io/name: demo-sdm
    app.kubernetes.io/part-of: demo-sdm
    app.kubernetes.io/managed-by: atomist
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sdm
  namespace: sdm
  labels:
    app.kubernetes.io/name: demo-sdm
    app.kubernetes.io/part-of: demo-sdm
    app.kubernetes.io/managed-by: atomist
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: demo-sdm
  namespace: sdm
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: demo-sdm
  namespace: sdm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-sdm
subjects:
  - kind: ServiceAccount
    name: demo-sdm
    namespace: sdm
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-sdm
  namespace: sdm
  labels:
    app.kubernetes.io/name: demo-sdm
    app.kubernetes.io/part-of: demo-sdm
    app.kubernetes.io/managed-by: atomist
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-sdm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-sdm
        app.kubernetes.io/part-of: demo-sdm
        app.kubernetes.io/managed-by: atomist
        app.kubernetes.io/version: "1"
    spec:
      serviceAccountName: demo-sdm
      containers:
        - name: demo-sdm
          image: atomist/demo-sdm:1.0.1-master.20190117105421
          imagePullPolicy: IfNotPresent
          env:
            - name: ATOMIST_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FORCE_COLOR
              value: "1"
            - name: ATOMIST_GOAL_SCHEDULER
              value: kubernetes
            - name: ATOMIST_CONFIG_PATH
              value: /opt/atm/client.config.json
          ports:
            - name: http
              containerPort: 2866
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 3
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 3
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 2000m
              memory: 3000Mi
            requests:
              cpu: 500m
              memory: 1000Mi
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: demo-sdm
              mountPath: /opt/atm
              readOnly: true
            - name: data
              mountPath: /opt/data
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: demo-sdm
          secret:
            defaultMode: 256
            secretName: demo-sdm
        - name: data
          hostPath:
            path: /mnt/disks/ssd0/data/demo-sdm
            type: DirectoryOrCreate
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
